# Generated by Django 5.1.4 on 2024-12-25 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0002_remove_table_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='remark',
        ),
    ]
